version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing SAM CLI..."
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building Lambda function..."
      - sam build
      - echo "Packaging for deployment..."
      - sam package --output-template-file outputTemplate.yaml --s3-bucket my-lambda-artifacts
artifacts:
  files:
    - outputTemplate.yaml
